stages:
  - build
  - test
  - analyze
  - deploy

maven-build:
  stage: build
  environment: staging
  script:
    - "mvn -DskipTests clean compile"

maven-test:
  stage: test
  environment: staging
  script:
    - "mvn test"

maven-deploy:
  stage: deploy
  environment: staging
  script:
    - "mvn deploy -DskipTests -DperformRelease"
  only:
    - /^master$/
    - /^dev$/
    - /^deploy-.*$/

#sonar-analyze:
#  stage: analyze
#  environment: staging
#  script:
#    - mvn -Ptest clean verify sonar:sonar
#      -DskipTests
#      -Dsonar.projectKey="$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
#      -Dsonar.projectName="$CI_PROJECT_NAME · $CI_COMMIT_REF_NAME"
#      -Dsonar.host.url="https://sonar.tools.kobalt-si.fr"
