<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.iglooproject.components</groupId>
	<artifactId>bindgen-bindings-java</artifactId>
	<version>4.1.0-SNAPSHOT</version>
	
	<name>JavaBindings @Bindable class</name>
	<description>@Bindable class that triggers java type binding generation</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<bindgen.version>7.0.0</bindgen.version>
		<slf4j.version>2.0.19</slf4j.version>
		
		<maven-clean-plugin.version>3.5.0</maven-clean-plugin.version>
		<maven-jar-plugin.version>3.5.1</maven-jar-plugin.version>
		<maven-site-plugin.version>3.22.0</maven-site-plugin.version>
		<maven-install-plugin.version>3.2.0</maven-install-plugin.version>
		<maven-resources-plugin.version>3.5.0</maven-resources-plugin.version>
		<maven-surefire-plugin.version>3.6.0</maven-surefire-plugin.version>
		<maven-compiler-plugin.version>3.16.0</maven-compiler-plugin.version>
		<maven-enforcer-plugin.version>3.6.3</maven-enforcer-plugin.version>
		<maven.gitflow-maven-plugin.version>1.21.0</maven.gitflow-maven-plugin.version>
		<maven-versions-plugin.version>2.22.0</maven-versions-plugin.version>
		<animal-sniffer-maven-plugin.version>1.28</animal-sniffer-maven-plugin.version>
		<maven-deploy.version>3.2.0</maven-deploy.version>
		<maven-source.version>3.4.0</maven-source.version>
		<maven-javadoc.version>3.12.0</maven-javadoc.version>
		<maven-dependency-plugin.version>3.11.0</maven-dependency-plugin.version>
		
		<jdk.version>25</jdk.version>
		<minimal.jdk.version>25</minimal.jdk.version>
		<minimal.maven.version>3.3</minimal.maven.version>
	</properties>

	<dependencies>
		<!-- bindgen generator and bases classes -->
		<dependency>
			<groupId>org.bindgen</groupId>
			<artifactId>bindgen</artifactId>
			<version>${bindgen.version}</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>${maven-dependency-plugin.version}</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>com.amashchenko.maven.plugin</groupId>
				<artifactId>gitflow-maven-plugin</artifactId>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-clean-plugin</artifactId>
					<version>${maven-clean-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>${maven-jar-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-install-plugin</artifactId>
					<version>${maven-install-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-resources-plugin</artifactId>
					<version>${maven-resources-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>${maven-surefire-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-site-plugin</artifactId>
					<version>${maven-site-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${maven-compiler-plugin.version}</version>
					<configuration>
						<proc>none</proc>
						<source>${jdk.version}</source>
						<target>${jdk.version}</target>
						<release>${jdk.version}</release>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-enforcer-plugin</artifactId>
					<version>${maven-enforcer-plugin.version}</version>
					<executions>
						<execution>
							<id>enforce</id>
							<goals>
								<goal>enforce</goal>
							</goals>
							<configuration>
								<rules>
									<requireUpperBoundDeps />
									<requireMavenVersion>
										<version>[${minimal.maven.version},)</version>
									</requireMavenVersion>
									<requireJavaVersion>
										<version>${minimal.jdk.version}</version>
									</requireJavaVersion>
								</rules>
							</configuration>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>com.amashchenko.maven.plugin</groupId>
					<artifactId>gitflow-maven-plugin</artifactId>
					<version>${maven.gitflow-maven-plugin.version}</version>
					<configuration>
						<gitFlowConfig>
							<productionBranch>master</productionBranch>
							<developmentBranch>dev</developmentBranch>
							<featureBranchPrefix>ft-</featureBranchPrefix>
							<releaseBranchPrefix>rl-</releaseBranchPrefix>
							<hotfixBranchPrefix>hf-</hotfixBranchPrefix>
							<versionTagPrefix>v</versionTagPrefix>
							<origin>origin</origin>
						</gitFlowConfig>
						<skipFeatureVersion>true</skipFeatureVersion>
						<!-- do not run verify, done on CI -->
						<skipTestProject>true</skipTestProject>
						<!-- In X.Y.Z, update Y -->
						<versionDigitToIncrement>1</versionDigitToIncrement>
						<!-- do not push during release; we perform this independently-->
						<pushRemote>false</pushRemote>
						<!-- build project during release -->
						<installProject>true</installProject>
						<!-- ensure all modules are processed by versions: calls -->
						<argLine>-DskipTests=true -DprocessAllModules=true -DskipResolution=true</argLine>
						<!-- print subcommand output -->
						<verbose>true</verbose>
						<!-- Needed as it implies project reloading during versioning, and triggers resolution failure -->
						<updateOutputTimestamp>false</updateOutputTimestamp>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-deploy-plugin</artifactId>
					<version>${maven-deploy.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-source-plugin</artifactId>
					<version>${maven-source.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-javadoc-plugin</artifactId>
					<version>${maven-javadoc.version}</version>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>versions-maven-plugin</artifactId>
					<version>${maven-versions-plugin.version}</version>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<scm>
		<url>git@github.com:igloo-project/bindgen-bindings-java.git</url>
		<connection>scm:git:git@github.com:igloo-project/bindgen-bindings-java.git</connection>
		<developerConnection>scm:git:git@github.com:igloo-project/bindgen-bindings-java.git</developerConnection>
		<tag>HEAD</tag>
	</scm>

	<repositories>
		<repository>
			<id>nexus-igloo-releases</id>
			<name>Nexus Kobalt Releases</name>
			<url>https://nexus.tools.kobalt.fr/repository/igloo-releases/</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>nexus-igloo-snapshots</id>
			<name>Nexus Kobalt Snapshots</name>
			<url>https://nexus.tools.kobalt.fr/repository/igloo-snapshots/</url>
			<releases>
				<enabled>true</enabled>
			</releases>
		</repository>
	</repositories>

	<distributionManagement>
		<repository>
			<id>nexus-igloo-releases</id>
			<name>Nexus Igloo Releases</name>
			<url>https://nexus.tools.kobalt.fr/repository/igloo-releases/</url>
		</repository>
		<snapshotRepository>
			<id>nexus-igloo-snapshots</id>
			<name>Nexus Igloo Snapshots</name>
			<url>https://nexus.tools.kobalt.fr/repository/igloo-snapshots/</url>
		</snapshotRepository>
	</distributionManagement>
</project>
